services:
  app:
    build: .
    platform: linux/amd64
    container_name: qubit_control_sim
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src:/app
    command: python main.py
