[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
license = "LicenseRef-Qblox"
license-files = ["LICENSES/*.txt"]
name = "qblox-sim"
version = "0.1.0"
description = "Simulation utilities for Qblox Scheduler using QuTiP"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "qblox-instruments==1.1.1",
    "qblox-scheduler==1.0.0b3",
    "q1simulator",
    "qutip>=4.7.0",
    "numpy>=1.22.0, <2.0.0",
    "scipy",
    "pandas",
    "matplotlib",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "jupyter",
    "ipykernel",
    "ruff",
    "pyright",
    "typos",
    "vulture",
    "mdformat",
    "commitizen"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
target-version = "py311"
exclude = [
    "notebooks",
    "examples",
    ".venv",
    "build",
    "dist"
]

[tool.pyright]
pythonVersion = "3.11"
include = ["src", "tests"]
exclude = [
    "**/node_modules",
    ".conda",
    "**/__pycache__",
    "**/.*",
    "notebooks",
    "examples"
]
reportMissingTypeStubs = false
reportUnknownMemberType = false